In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [17]:
df = pd.read_csv("C:\\Users\\Satish\\Downloads\\DataSets\\weight-height.csv")
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [18]:
dummy = pd.get_dummies(df["Gender"])
dummy

Female  Male
0          0     1
1          0     1
2          0     1
3          0     1
4          0     1
...      ...   ...
9995       1     0
9996       1     0
9997       1     0
9998       1     0
9999       1     0

[10000 rows x 2 columns]

In [19]:
dummy1 = pd.get_dummies(df["Gender"], drop_first = True)
dummy1

Male
0        1
1        1
2        1
3        1
4        1
...    ...
9995     0
9996     0
9997     0
9998     0
9999     0

[10000 rows x 1 columns]

In [20]:
dummy = dummy.drop("Male",axis = 1)
dummy

Female
0          0
1          0
2          0
3          0
4          0
...      ...
9995       1
9996       1
9997       1
9998       1
9999       1

[10000 rows x 1 columns]

In [21]:
df1 = pd.concat([dummy1,df],axis = 1)
df1.head()

Male Gender     Height      Weight
0     1   Male  73.847017  241.893563
1     1   Male  68.781904  162.310473
2     1   Male  74.110105  212.740856
3     1   Male  71.730978  220.042470
4     1   Male  69.881796  206.349801

In [22]:
df1 = df1.drop(["Gender"],axis = 1)
df1.head()

Male     Height      Weight
0     1  73.847017  241.893563
1     1  68.781904  162.310473
2     1  74.110105  212.740856
3     1  71.730978  220.042470
4     1  69.881796  206.349801

In [24]:
x = df1[["Male","Height"]]

In [25]:
x.sample(5)

Male     Height
9814     0  60.442250
7319     0  66.683512
881      1  65.718179
4945     1  67.615954
3192     1  66.487231

In [26]:
y = df1[["Weight"]]

In [50]:
y.sample(5)

Weight
819   228.872991
7641  162.907243
3919  214.172512
7121  150.441300
1009  167.910729

In [27]:
from sklearn.model_selection import train_test_split

In [29]:
 x_train ,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.30)

In [30]:
x_train.shape

(7000, 2)

In [31]:
x_test.shape

(3000, 2)

In [32]:
y_train.shape

(7000, 1)

In [33]:
y_test.shape

(3000, 1)

In [37]:
x_train.sample(5)

Male     Height
9340     0  62.800611
1848     1  68.786574
6426     0  61.759341
5182     0  57.313903
5804     0  63.732847

In [38]:
y_train.sample(5)

Weight
4720  211.627538
996   186.358702
9732  138.439090
5842  122.515320
2228  166.776838

In [35]:
from sklearn.linear_model import LinearRegression

In [36]:
model = LinearRegression()

In [39]:
model.fit(x_train,y_train)

LinearRegression()

In [44]:
model.predict(x_test)

array([[211.33613856],
       [191.11019885],
       [134.18133858],
       ...,
       [156.24203516],
       [132.0763926 ],
       [195.1887989 ]])

In [45]:
model.score(x_test,y_test)

0.9059041611216073

In [52]:
model.predict([[1,70.21]])

array([[194.03559812]])

In [53]:
model.predict([[0,65]])

array([[143.63174196]])